global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 15s

    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "hotel_booking"

    scrape_interval: 15s

    static_configs:
      - targets: [ "hotel_booking:8000" ]